// Generated by codex_silentgear_mercury_titanium_depth_pass.py
const GIGANI_MERCURY_TITANIUM_DEPTH_ITEMS = [
  ['mercury_droplet', 'Mercury Droplet'],
  ['conductive_copper', 'Conductive Copper Ingot'],
  ['quicksilver_amalgam', 'Quicksilver Amalgam Ingot'],
  ['mercury_silver_amalgam', 'Mercury-Silver Amalgam Ingot'],
  ['mercury_gold_amalgam', 'Mercury-Gold Amalgam Ingot'],
  ['mercury_copper_amalgam', 'Mercury-Copper Amalgam Ingot'],
  ['nitinol', 'Nitinol Ingot'],
  ['titanium_aluminide', 'Titanium Aluminide Ingot'],
  ['titanium_aluminum_vanadium_alloy', 'Titanium-Aluminum-Vanadium Alloy Ingot'],
  ['beta_c_titanium_alloy', 'Beta-C Titanium Alloy Ingot'],
  ['titanium_molybdenum_alloy', 'Titanium-Molybdenum Alloy Ingot'],
  ['titanium_vanadium_chromium_alloy', 'Titanium-Vanadium-Chromium Alloy Ingot'],
  ['titanium_nitride_ceramic', 'Titanium Nitride Ceramic Ingot'],
  ['titanium_diboride_cermet', 'Titanium Diboride Cermet Ingot'],
  ['titanium_silicon_carbide_max_phase', 'Titanium Silicon Carbide MAX Phase Ingot'],
  ['titanium_tungsten_molybdenum_tool_steel', 'Titanium-Tungsten-Molybdenum Tool Steel Ingot'],
  ['titanium_platinum_iridium_surgical_alloy', 'Titanium-Platinum-Iridium Surgical Alloy Ingot'],
  ['titanium_osmium_impact_alloy', 'Titanium-Osmium Impact Alloy Ingot'],
  ['titanium_chromium_nitride_alloy', 'Titanium-Chromium Nitride Alloy Ingot'],
  ['aluminum_lithium', 'Aluminum-Lithium Ingot'],
  ['aluminum_silicon', 'Aluminum-Silicon Ingot'],
  ['cobalt_chrome', 'Cobalt-Chrome Ingot'],
  ['hafnium_boride', 'Hafnium Boride Ingot'],
  ['superalloy_haynes', 'Haynes Superalloy Ingot'],
  ['superalloy_rene', 'Rene Superalloy Ingot'],
  ['tantalum_tungsten_hafnium', 'Tantalum-Tungsten-Hafnium Ingot'],
  ['yttrium_aluminum_garnet', 'Yttrium Aluminum Garnet Ingot'],
]

StartupEvents.registry('item', event => {
  GIGANI_MERCURY_TITANIUM_DEPTH_ITEMS.forEach(([id, displayName]) => {
    event.create(id).displayName(displayName)
  })
})
