// Generated by codex_generate_silentgear_depth_pass.py
const GIGANI_SILENTGEAR_DEPTH_ITEMS = [
  ['fluxwoven_core', 'Fluxwoven Core'],
  ['null_vector_core', 'Null Vector Core'],
  ['adamant_impact_core', 'Adamant Impact Core'],
  ['divine_spell_core', 'Divine Spell Core'],
  ['frostfire_conflux_core', 'Frostfire Conflux Core'],
  ['alchemical_honey_core', 'Alchemical Honey Core'],
  ['resonant_scrying_core', 'Resonant Scrying Core'],
  ['withered_phylactery_core', 'Withered Phylactery Core'],
  ['mekasonic_overdrive_core', 'Mekasonic Overdrive Core'],
  ['infinite_singularity_core', 'Infinite Singularity Core'],
  ['phantom_silk_lining', 'Phantom Silk Lining'],
  ['soulthread_binding', 'Soulthread Binding'],
  ['glistering_honey_lining', 'Glistering Honey Lining'],
  ['warded_shulker_lining', 'Warded Shulker Lining'],
]

StartupEvents.registry('item', event => {
  GIGANI_SILENTGEAR_DEPTH_ITEMS.forEach(([id, displayName]) => {
    event.create(id).displayName(displayName)
  })
})
