// Generated by codex_titan_tempad_bop_silentgear_bridge.py
const GIGANI_TITAN_TEMPAD_BOP_BRIDGE_ITEMS = [
  ['rutilmenite_tool_steel', 'Rutilmenite Tool Steel Ingot'],
  ['rose_quartz_titanium_laminate', 'Rose Quartz Titanium Laminate Ingot'],
  ['chronotitanium_alloy', 'Chronotitanium Alloy Ingot'],
  ['vroomanite_reactor_alloy', 'Vroomanite Reactor Alloy Ingot'],
]

StartupEvents.registry('item', event => {
  GIGANI_TITAN_TEMPAD_BOP_BRIDGE_ITEMS.forEach(([id, displayName]) => {
    event.create(id).displayName(displayName)
  })
})
