#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Jun 30 09:33:06 EDT 2026
allowUnknownShaders=true
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=16
shaderPack=MakeUp-UltraFast-9.5b.zip
