package com.gigani.grindinggear;

import net.minecraft.world.item.Item;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.fml.common.Mod;
import net.neoforged.neoforge.registries.DeferredRegister;

@Mod(GrindingGear.MODID)
public final class GrindingGear {
  public static final String MODID = "grindinggear";

  private static final String[] ITEM_IDS = {
      "tungsten_carbide_steel",
      "nickel_tungsten_tool_steel",
      "titanium_tungsten_steel",
      "osmium_tungsten_steel",
      "iridium_tungsten_steel",
      "platinum_tungsten_steel",
      "uranium_tungsten_steel",
      "chromium_tungsten_steel",
      "titanium_carbide_steel",
      "osmium_carbide_steel",
      "iridium_carbide_steel",
      "platinum_carbide_steel",
      "netherite_carbide_steel",
      "obsidian_carbide_steel",
      "diamond_matrix_steel",
      "sapphire_matrix_steel",
      "ruby_matrix_steel",
      "peridot_matrix_steel",
      "fluorite_hardened_steel",
      "uranium_hardened_steel",
      "redstone_hardened_steel",
      "glowstone_tempered_steel",
      "ender_tempered_steel",
      "shulker_reinforced_steel",
      "nether_quartz_steel",
      "lapis_laced_steel",
      "amethyst_tempered_steel",
      "cinnabar_tempered_steel",
      "sulfurized_steel",
      "salt_quenched_steel",
      "aluminum_nickel_superalloy",
      "aluminum_titanium_superalloy",
      "nickel_iridium_superalloy",
      "nickel_osmium_superalloy",
      "nickel_platinum_superalloy",
      "nickel_uranium_superalloy",
      "titanium_iridium_superalloy",
      "titanium_osmium_superalloy",
      "titanium_platinum_superalloy",
      "titanium_uranium_superalloy",
      "platinum_iridium_superalloy",
      "osmium_iridium_superalloy",
      "platinum_osmium_superalloy",
      "uranium_iridium_superalloy",
      "uranium_osmium_superalloy",
      "uranium_platinum_superalloy",
      "aluminum_zinc_dural_alloy",
      "aluminum_copper_aeralloy",
      "aluminum_silver_aeralloy",
      "aluminum_tin_bearing_alloy",
      "aluminum_osmium_light_alloy",
      "aluminum_iridium_light_alloy",
      "aluminum_platinum_light_alloy",
      "nickel_zinc_casting_alloy",
      "tin_nickel_bearing_alloy",
      "lead_nickel_bearing_alloy",
      "tin_silver_bearing_alloy",
      "tin_platinum_bearing_alloy",
      "copper_silver_conductor_alloy",
      "copper_gold_conductor_alloy",
      "copper_platinum_conductor_alloy",
      "copper_iridium_conductor_alloy",
      "copper_osmium_conductor_alloy",
      "copper_uranium_conductor_alloy",
      "redstone_copper_conductive_alloy",
      "redstone_gold_conductive_alloy",
      "redstone_silver_conductive_alloy",
      "redstone_platinum_conductive_alloy",
      "redstone_iridium_conductive_alloy",
      "glowstone_silver_radiant_alloy",
      "glowstone_gold_radiant_alloy",
      "glowstone_platinum_radiant_alloy",
      "glowstone_iridium_radiant_alloy",
      "glowstone_osmium_radiant_alloy",
      "ender_nickel_void_alloy",
      "ender_osmium_void_alloy",
      "ender_iridium_void_alloy",
      "ender_platinum_void_alloy",
      "ender_uranium_void_alloy",
      "ender_netherite_void_alloy",
      "obsidian_nickel_dark_alloy",
      "obsidian_osmium_dark_alloy",
      "obsidian_iridium_dark_alloy",
      "obsidian_platinum_dark_alloy",
      "obsidian_netherite_dark_alloy",
      "amethyst_silver_resonant_alloy",
      "amethyst_gold_resonant_alloy",
      "amethyst_platinum_resonant_alloy",
      "quartz_silver_resonant_alloy",
      "quartz_gold_resonant_alloy",
      "sapphire_silver_arcane_alloy",
      "sapphire_platinum_arcane_alloy",
      "ruby_gold_arcane_alloy",
      "ruby_iridium_arcane_alloy",
      "peridot_nickel_arcane_alloy",
      "peridot_osmium_arcane_alloy",
      "fluorite_aluminum_flux_alloy",
      "fluorite_copper_flux_alloy",
      "cinnabar_silver_catalytic_alloy",
      "cinnabar_uranium_catalytic_alloy",
      "field_cascade_alloy",
      "industrial_cascade_alloy",
      "resonant_cascade_alloy",
      "terminus_cascade_alloy",
      "fluxwoven_core",
      "null_vector_core",
      "adamant_impact_core",
      "divine_spell_core",
      "frostfire_conflux_core",
      "alchemical_honey_core",
      "resonant_scrying_core",
      "withered_phylactery_core",
      "mekasonic_overdrive_core",
      "infinite_singularity_core",
      "phantom_silk_lining",
      "soulthread_binding",
      "glistering_honey_lining",
      "warded_shulker_lining",
      "mercury_droplet",
      "conductive_copper",
      "quicksilver_amalgam",
      "mercury_silver_amalgam",
      "mercury_gold_amalgam",
      "mercury_copper_amalgam",
      "nitinol",
      "titanium_aluminide",
      "titanium_aluminum_vanadium_alloy",
      "beta_c_titanium_alloy",
      "titanium_molybdenum_alloy",
      "titanium_vanadium_chromium_alloy",
      "titanium_nitride_ceramic",
      "titanium_diboride_cermet",
      "titanium_silicon_carbide_max_phase",
      "titanium_tungsten_molybdenum_tool_steel",
      "titanium_platinum_iridium_surgical_alloy",
      "titanium_osmium_impact_alloy",
      "titanium_chromium_nitride_alloy",
      "aluminum_lithium",
      "aluminum_silicon",
      "cobalt_chrome",
      "hafnium_boride",
      "superalloy_haynes",
      "superalloy_rene",
      "tantalum_tungsten_hafnium",
      "yttrium_aluminum_garnet"
  };

  private static final DeferredRegister.Items ITEMS = DeferredRegister.createItems("kubejs");

  static {
    for (String id : ITEM_IDS) {
      ITEMS.registerSimpleItem(id, new Item.Properties());
    }
  }

  public GrindingGear(IEventBus modEventBus) {
    ITEMS.register(modEventBus);
  }
}